### ISSUE TITLE
This example does not work.

### ISSUE THREAD

**Issue by gustawdaniel** [nwneisen/vuepress-blog-example#1]
After cloning and typing command 

```
vuepress dev
```

I see

![Screenshot from 2019-07-05 11-26-44](https://user-images.githubusercontent.com/16663028/60712662-cc2bd680-9f17-11e9-8965-3a150a9c4fd1.png)

But I suspected list of posts.

**Comment by jpeyret** [comment]
pretty much what I found too.

**Comment by gustawdaniel** [comment]
It is possible. I have seen some different structures of vuepress/theme files. I have 

```
.vuepress/theme/
├── Index.vue    - main page with loop over posts 
├── Layout.vue  - common layout
├── Single.vue   - single blog post
```

Working example 

> https://github.com/gustawdaniel/blog.gustawdaniel.com

I hope maintainer will fix it because of repositories like this are very helpful for community for learning. 

Best wishes.

**Comment by nwneisen** [comment]
Thanks for pointing this out and sorry for the late reply.  The blog plugin for this example has been completely rewritten by the vuepress maintainers.  Information for this change can be found at https://github.com/vuejs/vuepress/issues/36.  I'm am no longer maintaining this example and will be archiving the repo to avoid confusion.
